### ISSUE TITLE
coef_layers and coef_fusion

### ISSUE THREAD

**Issue by wangqiang-codes** [baoyujing/HDMI#1]
Hello, I am very glad to read your paper. Could you please tell me how to set 'coef_layers' and 'coef_fusion'? How can I set these parameters to achieve the results in your paper?

**Comment by baoyujing** [comment]
Thanks for your interest. Sorry that I don't remember the exact settings for each dataset. However, you can try the following reference settings:
ACM: coef_layers=[2, 1, 0.001], coef_fusion=[1, 0.001, 0.0001], same_discriminator=False
IMDB: coef_layers=[0.1, 2, 0.0001], coef_fusion=[0.001, 0.001, 0.0001], same_discriminator=True
DBLP: coef_layers=[1, 1, 2], coef_fusion=[1, 0.5, 2], same_discriminator=False
Amazon: coef_layers=[1, 2, 0.001], coef_fusion=[0.01, 0.1, 0.001], same_discriminator=False
