### ISSUE TITLE
Results of semi-supervised methods

### ISSUE THREAD

**Issue by CurryTang** [baoyujing/HDMI#2]
Hi! I notice that some semi-supervised methods such as GCN are also included in the experiment part. I wonder how you test the accuracy of these semi-supervised methods?

**Comment by baoyujing** [comment]
The results of baselines are copied from the DMGI paper: [Unsupervised Attributed Multiplex Network Embedding](https://arxiv.org/abs/1911.06750). Maybe you can ask the authors of the DMGI paper.
